#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
backend webservers
    balance roundrobin
    server 36572-web-01 54.208.128.114 check
    server 36572-web-02 3.238.94.60 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
